/**
 * 事件派发常量
 */
export const TEST_ACTION = 'TEST_ACTION';
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
/**
 * 获取trending的常量
 */
export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES';
export const FETCH_DEVOLOPERS = 'FETCH_DEVOLOPERS';
export const FETCH_LANGUAGES = 'FETCH_LANGUAGES';
export const FETCH_SPOKEN_LANGUAGES = 'FETCH_SPOKEN_LANGUAGES';
export const FETCH_RANDOM_REPOSITORIES = 'FETCH_RANDOM_REPOSITORIES';
